// LIST OF ALL EMPLOYMENT TYPES
export const EMPLOYMENT_TYPES = ["Full-Time", "Part-Time", "Contract", "Volunteering", "Freelancer"];

// LIST OF CAMPUS OPTIONS
export const CAMPUS_OPTIONS = ["On Campus", "Off Campus"];

// LIST OF ROOMS OPTIONS
export const ROOMS_OPTIONS = ["Single Room", "Double Rooms", "Triple Rooms", "Suit-Style Rooms"];

// LIST OF ALL TERMS
export const TERMS = [
  "2023", 
  "2022", 
  "2021", 
  "2020", 
  "2019", 
  "2018", 
  "2017", 
  "2016", 
  "2014",
  "2013",
  "2012",
  "2011",
  "2010",
  "2009",
  "2008",
  "2007",
  "2006",
  "2005",
  "2004",
  "2003",
  "2002",
  "2001",
  "2000",
];

// LIST OF CLUB CATEGORIES
export const CLUB_CATEGORIES = [
  "Academic",
  "Advocacy",
  "Campus Media",
  "Cultural",
  "Greek",
  "Hobby",
  "Lifestyle",
  "Performing Arts",
  "Political",
  "Public Service",
  "Spiritual",
  "Sports",
  "Technology",
];

// LIST OF INDUSTRIES
export const INDUSTRIES = [
  "Aerospace",
  "Agriculture",
  "Construction",
  "Education",
  "Energy",
  "Entertainment",
  "Fashion",
  "Finance",
  "Food",
  "Health Care",
  "Hospitality",
  "Manufacturing",
  "Marketing",
  "Media",
  "Mining",
  "Pharmaceutical",
  "Telecommunication",
  "Technology",
  "Transportation",
];

// LIST OF JOB
export const JOB_TITLES = [
  "Academic Librarian",
  "Accountant",
  "Accounting Technician",
  "Actuary",
  "Adult Nurse",
  "Advertising Copywriter",
  "Advice Worker",
  "Aeronautical Engineer",
  "Agricultural Consultant",
  "Agricultural Manager",
  "Air Traffic Controller",
  "Airline Cabin Crew",
  "Amenity Horticulturist",
  "Analytical Chemist",
  "Animal Nutritionist",
  "Animator",
  "Archaeologist",
  "Architect",
  "Archivist",
  "Armed Forces Officer",
  "AromaTherapist",
  "Art Therapist",
  "Arts Administrator",
  "Auditor",
  "Automotive Engineer",
  "Barrister",
  "Barrister's Clerk",
  "Bid Manager",
  "Bilingual Secretary",
  "Biomedical Engineer",
  "Biomedical Scientist",
  "Biotechnologist",
  "Border Force Officer",
  "Brand Manager",
  "Broadcasting Presenter",
  "Building Services Engineer",
  "Building Surveyor",
  "Business Analyst",
  "Camera Operator",
  "Careers Adviser",
  "Careers Consultant",
  "Cartographer",
  "Catering Manager",
  "Charities Administrator",
  "Charities Fundraiser",
  "Chemical (Process) Engineer",
  "Child PsychoTherapist",
  "Children's Nurse",
  "Chiropractor",
  "Civil Engineer",
  "Civil Service Administrator",
  "Clinical Biochemist",
  "Clinical Cytogeneticist",
  "Clinical Microbiologist",
  "Clinical Molecular Geneticist",
  "Clinical Research Associate",
  "Clinical Scientist",
  "Clothing Technologist",
  "Colour Technologist",
  "Commercial Airline Pilot",
  "Commercial Horticulturist",
  "Commercial/Residential Surveyor",
  "Commissioning Editor",
  "Commissioning Engineer",
  "Commodity Broker",
  "Communications Engineer",
  "Community Arts Worker",
  "Community Education Officer",
  "Community Worker",
  "Company Secretary",
  "Computer Sales Support",
  "Computer Scientist",
  "Conference Organiser",
  "Consultant",
  "Consumer Rights Adviser",
  "Corporate Banker",
  "Corporate Treasurer",
  "Counsellor",
  "Credit Analyst",
  "Crystallographer",
  "Curator",
  "Customs Officer",
  "Cyber Security Specialist",
  "Data Analyst",
  "Data Scientist",
  "Data Visualisation Analyst",
  "Database Administrator",
  "Debt/Dinance Adviser",
  "Dental Hygienist",
  "Dentist",
  "Design Engineer",
  "Design Manager",
  "DevOps Engineer",
  "Dietitian",
  "Diplomatic Service",
  "Doctor",
  "DramaTherapist",
  "Economist",
  "Editorial Assistant",
  "Education Administrator",
  "Electrical Engineer",
  "Electronics Engineer",
  "Employment Advice Worker",
  "Energy Conservation Officer",
  "Energy Consultant",
  "Engineering Geologist",
  "Environmental Health Officer",
  "Environmental Manager",
  "Environmental Scientist",
  "Equal Opportunities Officer",
  "Equality and Diversity Officer",
  "Ergonomist",
  "Estate Agent",
  "Estimator",
  "Exhibition Display Designer",
  "Exhibition Organiser",
  "Exploration Geologist",
  "Facilities Manager",
  "Field Trials Officer",
  "Financial Manager",
  "Fire Engineer",
  "Firefighter",
  "Fisheries Enforcement Officer",
  "Fitness Centre Manager",
  "Food Scientist",
  "Food Technologist",
  "Forensic Scientist",
  "Freight Forwarder",
  "Geneticist",
  "Geomatics/Land Surveyor",
  "Government Lawyer",
  "Government Research Officer",
  "Graphic Designer",
  "Health and Safety Adviser",
  "Health and Safety Inspector",
  "Health Promotion Specialist",
  "Health Service Manager",
  "Health Visitor",
  "Herbalist",
  "Heritage Manager",
  "Higher Education Administrator",
  "Higher Education Advice Worker",
  "Homeless Support Worker",
  "Horticultural Consultant",
  "Hotel Manager",
  "Housing Adviser",
  "Human Resources Officer",
  "Hydrologist",
  "Illustrator",
  "Immigration Officer",
  "Immunologist",
  "Industrial/Product Designer",
  "Information Scientist",
  "Information Systems Manager",
  "Information Technology Trainers",
  "Insurance Broker",
  "Insurance Claims Inspector",
  "Insurance Risk Surveyor",
  "Insurance Underwriter",
  "Interpreter",
  "Investment Analyst",
  "Investment Banker",
  "Investment FUnd Manager",
  "IT Consultant",
  "IT Support Analyst",
  "Journalist",
  "Laboratory Technician",
  "Land-based Engineer",
  "Landscape Architect",
  "Learning Disability Nurse",
  "Learning Mentor",
  "Lecturer",
  "Legal Executive",
  "Leisure Centre Manager",
  "Licensed Conveyancer",
  "Local Government administrator",
  "Local Government lawyer",
  "Distribution Manager",
  "Magazine Features Editor",
  "Magazine Journalist",
  "Maintenance Engineer",
  "Management accountant",
  "Manufacturing Engineer",
  "Manufacturing Machine Operator",
  "Manufacturing Toolmaker",
  "Marine Scientist",
  "Market Research Analyst",
  "Market Research Executive",
  "Marketing Assistant",
  "Marketing Executive",
  "Marketing Manager",
  "Materials Engineer",
  "Materials Specialist",
  "Mechanical Engineer",
  "Media Analyst",
  "Media Buyer",
  "Media Planner",
  "Medical Physicist",
  "Medical Representative",
  "Mental Health Nurse",
  "Metallurgist",
  "Meteorologist",
  "Microbiologist",
  "Midwife",
  "Mining Engineer",
  "Mobile Developer",
  "Multimedia Programmer",
  "Multimedia Specialists",
  "Museum Education Officer",
  "Museum Exhibition Officer",
  "Music Therapist",
  "Nanoscientist",
  "Nature Conservation Officer",
  "Naval Architect",
  "Network Administrator",
  "Nurse",
  "Nutritional Therapist",
  "Nutritionist",
  "Occupational Therapist",
  "Oceanographer",
  "Office Manager",
  "Operational Researcher",
  "Orthoptist",
  "Outdoor Pursuits Manager",
  "Packaging Technologist",
  "Paramedic",
  "Patent Attorney",
  "Patent Examiner",
  "Pension Scheme Manager",
  "Personal Assistant",
  "Petroleum Engineer",
  "Pharmacist",
  "Pharmacologist",
  "Pharmacovigilance Officer",
  "Photographer",
  "PhysioTherapist",
  "Picture Researcher",
  "Planning & Development Surveyor",
  "Planning Technician",
  "Plant Breeder",
  "Police Officer",
  "Political Party Agent",
  "Political Researcher",
  "Practice nurse",
  "Press Photographer",
  "Press Sub-editor",
  "Prison Officer",
  "Private Music Teacher",
  "Probation Officer",
  "Product Development Scientist",
  "Production Manager",
  "Programme Researcher",
  "Project Manager",
  "Psychologist",
  "PsychoTherapist",
  "Public Affairs Consultant",
  "Public House Manager",
  "Public Librarian",
  "Public Relations Officer",
  "QA Analyst",
  "Quality Assurance Manager",
  "Quantity Surveyor",
  "Records Manager",
  "Recruitment Consultant",
  "Recycling Officer",
  "Regulatory Affairs Officer",
  "Research Chemist",
  "Research Scientist",
  "Restaurant Manager",
  "Retail Banker",
  "Retail Buyer",
  "Retail Manager",
  "Retail Merchandiser",
  "Retail Pharmacist",
  "Sales Executive",
  "Scene of Crime Officer",
  "Secretary",
  "Seismic Interpreter",
  "Site Engineer",
  "Site Manager",
  "Social Researcher",
  "Social Worker",
  "Software Developer",
  "Software Engineer",
  "Soil Scientist",
  "Solicitor",
  "Speech and Language Therapist",
  "Sports Coach",
  "Sports Development Officer",
  "Sports Therapist",
  "Statistician",
  "Stockbroker",
  "Structural Engineer",
  "Systems Analyst",
  "Systems Developer",
  "Tax Inspector",
  "Teacher",
  "Teaching/Classroom Assistant",
  "Technical Author",
  "Technical Sales Engineer",
  "TEFL/TESL Teacher",
  "Television Production Assistant",
  "Test Automation Developer",
  "Tour Guide",
  "Tour Operator",
  "Tour/Holiday Representative",
  "Tourism Officer",
  "Tourist Information Manager",
  "Town and Country Planner",
  "Toxicologist",
  "Trade Union Official",
  "Trade Union Research Officer",
  "Trader",
  "Trading Standards Officer",
  "Training and Development Officer",
  "Translator",
  "Transportation Planner",
  "Travel Agent",
  "TV/Film/Theatre Set Designer",
  "UX Designer",
  "Validation Engineer",
  "Veterinary Nurse",
  "Veterinary Surgeon",
  "Video Game Designer",
  "Video Game Developer",
  "Volunteer Work Organiser",
  "Waste Management Officer",
  "Water Conservation Officer",
  "Water Engineer",
  "Web Designer",
  "Web Developer",
  "Welfare Rights Adviser",
  "Writer",
  "Youth Worker"
];

// LIST OF US CITIES
export const CITIES = [
  "Anaheim, CA", 
  "Austin, TX", 
  "Boston, MA", 
  "Charlotte, NC", 
  "Chicago, IL", 
  "Cleveland, OH", 
  "Columbus, OH", 
  "Dallas, TX", 
  "Denver, CO", 
  "Detroit, MI", 
  "Fort Worth, TX", 
  "Fremont, CA", 
  "Fresno, CA", 
  "Houston, TX", 
  "Indianapolis, IN", 
  "Irvine, CA", 
  "Jacksonville, FL", 
  "Long Beach, CA", 
  "Los Angeles, CA",
   "Miami, FL", 
   "Nashville, TN", 
   "New Orleans, LA", 
   "New York, NY", 
   "Newark, NJ", 
   "Oakland, CA", 
   "Orlando, FL", 
   "Philadelphia, PA", 
   "Phoenix, AZ", 
   "Pittsburgh, PA", 
   "Plano, TX", 
   "Portland, OR", 
   "Richmond, VA", 
   "Riverside, CA", 
   "Sacramento, CA", 
   "San Antonio, TX", 
   "San Bernardino, CA", 
   "San Diego, CA", 
   "San Francisco, CA", 
   "San Jose, CA", 
   "Santa Ana, CA", 
   "Santa Clarita, CA", 
   "Seattle, WA", 
   "St. Louis, MO", 
   "Tampa, FL", 
   "Washington, DC"
  ];
