// LIST OF ALL EMPLOYMENT TYPES
export const EMPLOYMENT_TYPES = ["Full-Time", "Part-Time", "Contract", "Volunteering", "Freelancer"];

// LIST OF CAMPUS OPTIONS
export const CAMPUS_OPTIONS = ["On Campus", "Off Campus"];

// LIST OF ROOMS OPTIONS
export const ROOMS_OPTIONS = ["Single Room", "Double Rooms", "Triple Rooms", "Suit-Style Rooms"];

// LIST OF ALL TERMS
export const TERMS = [
  "2023", 
  "2022", 
  "2021", 
  "2020", 
  "2019", 
  "2018", 
  "2017", 
  "2016", 
  "2014",
  "2013",
  "2012",
  "2011",
  "2010",
  "2009",
  "2008",
  "2007",
  "2006",
  "2005",
  "2004",
  "2003",
  "2002",
  "2001",
  "2000",
];

// LIST OF ALL SCHOOL TERMS
export const SCHOOL_TERMS = [
  "Spring 2023", 
  "Winter 2023", 
  "Fall 2023", 
  "Summer 2023", 
  "Spring 2022", 
  "Winter 2022", 
  "Fall 2022", 
  "Summer 2022",
  "Spring 2021", 
  "Winter 2021", 
  "Fall 2021", 
  "Summer 2021", 
  "Spring 2020", 
  "Winter 2020", 
  "Fall 2020", 
  "Summer 2020", 
  "Spring 2019", 
  "Winter 2019", 
  "Fall 2019", 
  "Summer 2019", 
  "Spring 2018", 
  "Winter 2018", 
  "Fall 2018", 
  "Summer 2018",
  "Spring 2017",
  "Winter 2017",
  "Fall 2017",
  "Summer 2017",
  "Spring 2016",
  "Winter 2016",
  "Fall 2016",
  "Summer 2016",
  "Spring 2015",
  "Winter 2015",
  "Fall 2015",
  "Summer 2015",
  "Spring 2014",
  "Winter 2014",
  "Fall 2014",
  "Summer 2014",
  "Spring 2013",
  "Winter 2013",
  "Fall 2013",
  "Summer 2013",
  "Spring 2012",
  "Winter 2012",
  "Fall 2012",
  "Summer 2012",
  "Spring 2011",
  "Winter 2011",
  "Fall 2011",
  "Summer 2011",
  "Spring 2010",
  "Winter 2010",
  "Fall 2010",
  "Summer 2010",
  "Spring 2009",
  "Winter 2009",
  "Fall 2009",
  "Summer 2009",
  "Spring 2008",
  "Winter 2008",
  "Fall 2008",
  "Summer 2008",
  "Spring 2007",
  "Winter 2007",
  "Fall 2007",
  "Summer 2007",
  "Spring 2006",
  "Winter 2006",
  "Fall 2006",
  "Summer 2006",
  "Spring 2005",
  "Winter 2005",
  "Fall 2005",
  "Summer 2005",
  "Spring 2004",
  "Winter 2004",
  "Fall 2004",
  "Summer 2004",
  "Spring 2003",
  "Winter 2003",
  "Fall 2003",
  "Summer 2003",
  "Spring 2002",
  "Winter 2002",
  "Fall 2002",
  "Summer 2002",
  "Spring 2001",
  "Winter 2001",
  "Fall 2001",
  "Summer 2001",
  "Spring 2000",
  "Winter 2000",
  "Fall 2000",
  "Summer 2000",
];

// LIST OF CLUB CATEGORIES
export const CLUB_CATEGORIES = [
  "Academic",
  "Advocacy",
  "Campus Media",
  "Cultural",
  "Greek",
  "Hobby",
  "Lifestyle",
  "Performing Arts",
  "Political",
  "Public Service",
  "Spiritual",
  "Sports",
  "Technology",
];

// LIST OF INDUSTRIES
export const INDUSTRIES = [
  "Aerospace",
  "Agriculture",
  "Construction",
  "Education",
  "Energy",
  "Entertainment",
  "Fashion",
  "Finance",
  "Food",
  "Health Care",
  "Hospitality",
  "Manufacturing",
  "Marketing",
  "Media",
  "Mining",
  "Pharmaceutical",
  "Telecommunication",
  "Technology",
  "Transportation",
];

// LIST OF JOB
export const JOB_TITLES = [
  "Academic Librarian",
  "Accountant",
  "Accounting Technician",
  "Actuary",
  "Adult Nurse",
  "Advertising Copywriter",
  "Advice Worker",
  "Aeronautical Engineer",
  "Agricultural Consultant",
  "Agricultural Manager",
  "Air Traffic Controller",
  "Airline Cabin Crew",
  "Amenity Horticulturist",
  "Analytical Chemist",
  "Animal Nutritionist",
  "Animator",
  "Archaeologist",
  "Architect",
  "Archivist",
  "Armed Forces Officer",
  "AromaTherapist",
  "Art Therapist",
  "Arts Administrator",
  "Auditor",
  "Automotive Engineer",
  "Barrister",
  "Barrister's Clerk",
  "Bid Manager",
  "Bilingual Secretary",
  "Biomedical Engineer",
  "Biomedical Scientist",
  "Biotechnologist",
  "Border Force Officer",
  "Brand Manager",
  "Broadcasting Presenter",
  "Building Surveyor",
  "Business Analyst",
  "Camera Operator",
  "Careers Adviser",
  "Careers Consultant",
  "Cartographer",
  "Catering Manager",
  "Charities Administrator",
  "Charities Fundraiser",
  "Chemical Engineer",
  "Child PsychoTherapist",
  "Children's Nurse",
  "Chiropractor",
  "Civil Engineer",
  "Clinical Biochemist",
  "Clinical Cytogeneticist",
  "Clinical Microbiologist",
  "Clinical Scientist",
  "Clothing Technologist",
  "Colour Technologist",
  "Commissioning Editor",
  "Commissioning Engineer",
  "Commodity Broker",
  "Communications Engineer",
  "Community Arts Worker",
  "Community Worker",
  "Company Secretary",
  "Computer Scientist",
  "Conference Organiser",
  "Consultant",
  "Corporate Banker",
  "Corporate Treasurer",
  "Counsellor",
  "Credit Analyst",
  "Crystallographer",
  "Curator",
  "Customs Officer",
  "Data Analyst",
  "Data Scientist",
  "Database Administrator",
  "Dental Hygienist",
  "Dentist",
  "Design Engineer",
  "Design Manager",
  "DevOps Engineer",
  "Dietitian",
  "Diplomatic Service",
  "Doctor",
  "DramaTherapist",
  "Economist",
  "Editorial Assistant",
  "Electrical Engineer",
  "Electronics Engineer",
  "Energy Consultant",
  "Engineering Geologist",
  "Environmental Manager",
  "Environmental Scientist",
  "Ergonomist",
  "Estate Agent",
  "Estimator",
  "Exhibition Organiser",
  "Exploration Geologist",
  "Facilities Manager",
  "Field Trials Officer",
  "Financial Manager",
  "Fire Engineer",
  "Firefighter",
  "Fitness Centre Manager",
  "Food Scientist",
  "Food Technologist",
  "Forensic Scientist",
  "Freight Forwarder",
  "Geneticist",
  "Government Lawyer",
  "Graphic Designer",
  "Health Service Manager",
  "Health Visitor",
  "Herbalist",
  "Heritage Manager",
  "Homeless Support Worker",
  "Horticultural Consultant",
  "Hotel Manager",
  "Housing Adviser",
  "Human Resources Officer",
  "Hydrologist",
  "Illustrator",
  "Immigration Officer",
  "Immunologist",
  "Industrial Designer",
  "Information Scientist",
  "Insurance Broker",
  "Insurance Risk Surveyor",
  "Insurance Underwriter",
  "Interpreter",
  "Investment Analyst",
  "Investment Banker",
  "Investment FUnd Manager",
  "IT Consultant",
  "IT Support Analyst",
  "Journalist",
  "Laboratory Technician",
  "Land-based Engineer",
  "Landscape Architect",
  "Learning Mentor",
  "Lecturer",
  "Legal Executive",
  "Leisure Centre Manager",
  "Licensed Conveyancer",
  "Distribution Manager",
  "Magazine Journalist",
  "Maintenance Engineer",
  "Management accountant",
  "Manufacturing Engineer",
  "Manufacturing Toolmaker",
  "Marine Scientist",
  "Market Research Analyst",
  "Marketing Assistant",
  "Marketing Executive",
  "Marketing Manager",
  "Materials Engineer",
  "Materials Specialist",
  "Mechanical Engineer",
  "Media Analyst",
  "Media Buyer",
  "Media Planner",
  "Medical Physicist",
  "Medical Representative",
  "Mental Health Nurse",
  "Metallurgist",
  "Meteorologist",
  "Microbiologist",
  "Midwife",
  "Mining Engineer",
  "Mobile Developer",
  "Multimedia Programmer",
  "Multimedia Specialists",
  "Music Therapist",
  "Nanoscientist",
  "Naval Architect",
  "Network Administrator",
  "Nurse",
  "Nutritional Therapist",
  "Nutritionist",
  "Occupational Therapist",
  "Oceanographer",
  "Office Manager",
  "Operational Researcher",
  "Orthoptist",
  "Outdoor Pursuits Manager",
  "Packaging Technologist",
  "Paramedic",
  "Patent Attorney",
  "Patent Examiner",
  "Pension Scheme Manager",
  "Personal Assistant",
  "Petroleum Engineer",
  "Pharmacist",
  "Pharmacologist",
  "Photographer",
  "PhysioTherapist",
  "Picture Researcher",
  "Planning Technician",
  "Plant Breeder",
  "Police Officer",
  "Political Party Agent",
  "Political Researcher",
  "Practice nurse",
  "Press Photographer",
  "Press Sub-editor",
  "Prison Officer",
  "Private Music Teacher",
  "Probation Officer",
  "Production Manager",
  "Programme Researcher",
  "Project Manager",
  "Psychologist",
  "PsychoTherapist",
  "Public House Manager",
  "Public Librarian",
  "QA Analyst",
  "Quantity Surveyor",
  "Records Manager",
  "Recruitment Consultant",
  "Recycling Officer",
  "Research Chemist",
  "Research Scientist",
  "Restaurant Manager",
  "Retail Banker",
  "Retail Buyer",
  "Retail Manager",
  "Retail Merchandiser",
  "Retail Pharmacist",
  "Sales Executive",
  "Scene of Crime Officer",
  "Secretary",
  "Seismic Interpreter",
  "Site Engineer",
  "Site Manager",
  "Social Researcher",
  "Social Worker",
  "Software Developer",
  "Software Engineer",
  "Soil Scientist",
  "Solicitor",
  "Sports Coach",
  "Sports Therapist",
  "Statistician",
  "Stockbroker",
  "Structural Engineer",
  "Systems Analyst",
  "Systems Developer",
  "Tax Inspector",
  "Teacher",
  "Technical Author",
  "Technical Sales Engineer",
  "TEFL/TESL Teacher",
  "Test Automation Developer",
  "Tour Guide",
  "Tour Operator",
  "Tourism Officer",
  "Town and Country Planner",
  "Toxicologist",
  "Trade Union Official",
  "Trader",
  "Translator",
  "Transportation Planner",
  "Travel Agent",
  "UX Designer",
  "Validation Engineer",
  "Veterinary Nurse",
  "Veterinary Surgeon",
  "Video Game Designer",
  "Video Game Developer",
  "Water Engineer",
  "Web Designer",
  "Web Developer",
  "Welfare Rights Adviser",
  "Writer",
  "Youth Worker"
];

// LIST OF US CITIES
export const CITIES = [
  "Anaheim, CA", 
  "Austin, TX", 
  "Boston, MA", 
  "Charlotte, NC", 
  "Chicago, IL", 
  "Cleveland, OH", 
  "Columbus, OH", 
  "Dallas, TX", 
  "Denver, CO", 
  "Detroit, MI", 
  "Fort Worth, TX", 
  "Fremont, CA", 
  "Fresno, CA", 
  "Houston, TX", 
  "Indianapolis, IN", 
  "Irvine, CA", 
  "Jacksonville, FL", 
  "Long Beach, CA", 
  "Los Angeles, CA",
  "Miami, FL", 
  "Nashville, TN", 
  "New Orleans, LA", 
  "New York, NY", 
  "Newark, NJ", 
  "Oakland, CA", 
  "Orlando, FL", 
  "Philadelphia, PA", 
  "Phoenix, AZ", 
  "Pittsburgh, PA", 
  "Plano, TX", 
  "Portland, OR", 
  "Richmond, VA", 
  "Riverside, CA", 
  "Sacramento, CA", 
  "San Antonio, TX", 
  "San Bernardino, CA", 
  "San Diego, CA", 
  "San Francisco, CA", 
  "San Jose, CA", 
  "Santa Ana, CA", 
  "Santa Clarita, CA", 
  "Seattle, WA", 
  "St. Louis, MO", 
  "Tampa, FL", 
  "Washington, DC"
  ];
