---
- name: Run Update Content Playbook
  ansible.builtin.import_playbook: update_content.yml

- name: Run Update Backend Playbook
  ansible.builtin.import_playbook: update_backend.yml

- name: Run Update Frontend Playbook
  ansible.builtin.import_playbook: update_frontend.yml


